apiVersion: apps/v1
kind: Deployment
metadata:
  name: netcore-deployment
  labels:
    app: netcore
spec:
  replicas: 3
  template:
    metadata:
      name: netcore
      labels:
        app: netcore
    spec:
      containers:
      - name: netcore
        image: yuksektek.azurecr.io/razorwebtest:latest
        imagePullPolicy: Always
      restartPolicy: Always
  selector:
    matchLabels:
      app: netcore


---

apiVersion: v1
kind: Service
metadata:
  name: netcore-service
spec:
  selector:
    app: netcore
  ports:
    - port: 80
  type: LoadBalancer
  